name: main

on:
  push:
    branches:
      - main
jobs:
  hello_world:
   runs-on: ubuntu-18.04
   steps:
    - name: Echo message
      run: echo 'Hola mundo con github actions'
    - name: Math operation
      run: echo $(expr 7 + 7)